# Generated by Django 2.2.1 on 2019-06-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdbird', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
