# Generated by Django 2.2.1 on 2019-06-06 00:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('birdbird', '0002_auto_20190605_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='observer',
            field=models.ForeignKey(default=1, on_delete=False, related_name='sightings', to=settings.AUTH_USER_MODEL),
        ),
    ]
