# Generated by Django 2.2.1 on 2019-06-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdbird', '0003_sighting_observer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='address',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='photo_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='description',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='species',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='species',
            name='photo_url',
            field=models.CharField(max_length=300),
        ),
    ]
